{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tams-frontend.fullname" . | default "tams-frontend" }}
spec:
  rules:
    - host: {{ .Values.ingress.host | default "tams.example.com" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tams-frontend.fullname" . | default "tams-frontend" }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}


