apiVersion: v1
kind: Service
metadata:
  name: {{ include "tams-frontend.fullname" . | default "tams-frontend" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "tams-frontend.name" . | default "tams-frontend" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http


